array-callback-return example corrected in Readme.md for issue #1806
airbnb/javascript pull request #2072
Opened 2019-08-15 06:23 UTC by abhinavsharma629

2019-08-15 06:44 UTC, ljharb requested changes
Please fix all the linting errors.

However, the original issue doesn't actually have a clear solution yet, so a PR was premature.

2019-08-15 10:01 UTC, abhinavsharma629 commented
Can you please check. I removed them sir.

2019-08-15 22:42 UTC, ljharb requested changes
I'm still not clear on why reduces are better examples than filters?

2019-08-15 22:42 UTC, ljharb commented on README.md
> +      }, {});
```suggestion
    }, {});
```

2019-08-15 22:42 UTC, ljharb commented on README.md
> +      }, {});
```suggestion
    }, {});
```

2019-08-15 22:42 UTC, ljharb commented on README.md
> +      });
```suggestion
    });
```

2019-08-15 22:42 UTC, ljharb commented on README.md
> +      });
```suggestion
    });
```

2019-08-16 07:22 UTC, abhinavsharma629 commented
Reducers aren't better or less than filters, but I think for a newbie understanding the above example would be much simpler than the filter example as it clearly shows how an array is getting reduced and values returned and stored in a new array.

2019-08-16 22:17 UTC, ljharb commented
There's already reduce examples above it; the purpose of the section is to talk about callbacks - showing different kinds of callbacks, like filter predicates, is useful.

2026-04-16 05:52 UTC, ljharb commented
Closing; happy to reopen if there's interest in revisiting it.

2026-04-16 05:52 UTC, closed without merging