chore: enable not breaking changes features
airbnb/javascript pull request #2350
Opened 2020-12-04 20:56 UTC by rivajunior

I've searched by `TODO: enable` to see what could be already enabled, based on the comment below de rule.

Since `^6.8.0 || ^7.2.0` are already supported. Features added before those versions were enabled.

2020-12-04 22:17 UTC, ljharb requested changes

2020-12-04 22:17 UTC, ljharb commented on packages/eslint-config-airbnb-base/rules/best-practices.js
> -    'default-case-last': 'off',
eslint v6 is allowed, so this change would still constitute a breaking change.

2020-12-04 22:17 UTC, ljharb commented on packages/eslint-config-airbnb-base/rules/errors.js
> -    'no-loss-of-precision': 'off',
eslint v6 is allowed, so this change would still constitute a breaking change.

2020-12-04 22:17 UTC, ljharb commented on packages/eslint-config-airbnb-base/rules/errors.js
> -    'no-useless-backreference': 'off',
eslint v6 is allowed, so this change would still constitute a breaking change.

2020-12-04 22:17 UTC, ljharb commented on packages/eslint-config-airbnb-base/rules/es6.js
> -    'no-restricted-exports': ['off', {
eslint v6 is allowed, so this change would still constitute a breaking change.

2022-03-01 17:28 UTC, ljharb commented
@rivajunior there's still some changes that can remain in this PR, if you're willing to update it.

2022-05-07 02:06 UTC, rivajunior commented
> @rivajunior there's still some changes that can remain in this PR, if you're willing to update it.

@ljharb I will take a look in it again

2023-02-24 02:04 UTC, closed without merging