bump eslint-plugin-react-hooks peer dependency version
airbnb/javascript pull request #2356
Opened 2020-12-17 05:23 UTC by maco

Fixes #2355

2020-12-17 07:22 UTC, ljharb requested changes

2020-12-17 07:22 UTC, ljharb commented on packages/eslint-config-airbnb/package.json
> +    "eslint-plugin-react-hooks": "^4.2.0 || ^3 || ^2.3.0 || ^1.7.0"
let's keep this at v4.0.1, so it's less likely to be a breaking change.

we'll also need to update the matching devDependencies line.

2020-12-25 17:16 UTC, dustintheweb commented
ty, waiting for this fix 😅

2020-12-25 20:05 UTC, ljharb commented
@dustintheweb theres no reason anyone would ever need to wait for this - it’s a semver range. You can update eslint-plugin-react-hooks all by yourself, with no needed changes here.

2021-03-25 19:27 UTC, ljharb approved these changes

2021-03-25 19:49 UTC, merged