[guide] Removed broken URLs.
airbnb/javascript pull request #2598
Opened 2022-05-26 08:11 UTC by ApinisMikelis

2022-09-20 15:29 UTC, Edwinvalerio approved these changes
LGTM

2022-09-20 16:14 UTC, ljharb requested changes
Let's replace all these links with their archive.org equivalents, instead.

2022-09-20 16:14 UTC, ljharb commented on README.md
> -  - [String vs Array Concat](https://jsperf.com/string-vs-array-concat/2)
this should be https://web.archive.org/web/20200414200857/https://jsperf.com/string-vs-array-concat/2

2023-08-12 03:20 UTC, fetchapi approved these changes

2023-08-12 03:21 UTC, fetchapi requested changes
yeah

2026-04-16 05:59 UTC, ljharb commented
Fixed in #2667.

2026-04-16 05:59 UTC, closed without merging