Remove broken links and var keywords
airbnb/javascript pull request #2667
Opened 2022-10-29 23:06 UTC by mrna0

2022-10-30 03:02 UTC, ljharb requested changes

2022-10-30 03:02 UTC, ljharb commented on README.md
> +    const x = 1;
this isn’t removing *every* var in the document - either they’re all fine, or they all need to go, but we shouldn’t do it partially.

2022-10-30 03:02 UTC, ljharb commented on README.md
> -  - **National Geographic**: [natgeo](https://github.com/natgeo/)
i believe this is now at https://github.com/natgeosociety

2022-10-31 07:56 UTC, hossein13m approved these changes

2022-11-02 13:58 UTC, mrna0 commented
Hi @ljharb, if there is something wrong my commits, I can fix it or cancel my  pull request.

2022-11-10 21:48 UTC, slumericanB approved these changes

2022-11-10 22:08 UTC, ljharb commented
@mrna0 no, you’re fine - there’s just no rush. I’ll rebase it and land it soon.

2022-11-17 17:34 UTC, ljharb requested changes

2022-11-17 17:34 UTC, ljharb commented on README.md
> +        return this.value + value;
this is an incorrect change, since `this` will depend on the way `addValue` is called, but hardcoding `atom` will not.

2022-11-17 22:06 UTC, ljharb approved these changes

2022-11-17 22:09 UTC, merged