Added Object.hasOwn to section 3.7
airbnb/javascript pull request #2812
Opened 2023-08-15 15:01 UTC by savalaram-redkar

2023-08-15 16:42 UTC, ljharb requested changes

2023-08-15 17:21 UTC, savalaram-redkar commented on README.md
> +    > Why? These methods may be shadowed by properties on the object in question - consider `{ hasOwnProperty: false }` - or, the object may be a null object (`Object.create(null)`). In modern browse
noted, will do the suggested changes.

2023-08-16 05:19 UTC, savalaram-redkar commented on README.md
> +    > Why? These methods may be shadowed by properties on the object in question - consider `{ hasOwnProperty: false }` - or, the object may be a null object (`Object.create(null)`). In modern browse
@ljharb Done with the changes, please check.

2023-08-16 05:21 UTC, ljharb approved these changes

2023-08-16 05:28 UTC, merged