Fixed typos in README.md
airbnb/javascript pull request #2980
Opened 2024-05-10 14:30 UTC by teddy5518

Hello,

I have fixed wording in 4.2 to better doc clarity. The ``#`` in the word block does not have any meaning, and is not used throughout the document. Thus, I wanted to suggest to change ``[Array#push]`` to [`Array.push`] so that it increases readability and matches existing wording style  such as 4.4's ``Array.from`` .

Thank you

cc. @ljharb

2024-05-10 14:35 UTC, ljharb requested changes
`Array#push` is a convention commonly used in documentation to mean `Array.prototype.push`, which is why this change would make it incorrect.

2024-05-10 15:00 UTC, teddy5518 commented
Thank you for the knowledge! As a developer who is learning a lot from this style guide, I really appreciate your hard work and feedback. Thank you. :)

2024-06-05 10:35 UTC, saad4code commented
- **helllo**

- [test ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ]

2024-06-05 10:35 UTC, saad4code commented
> Thank you for the knowledge! As a developer who is learning a lot from this style guide, I really appreciate your hard work and feedback. Thank you. :)

2024-08-23 16:39 UTC, mx636 approved these changes

2024-08-23 16:40 UTC, closed without merging